kind: pipeline
type: kubernetes
name: default

workspace:
  path: /drone/src

steps:
  - name: build-cache
    image: node:lts-alpine
    commands:
      - "yarn install -W"
    when:
      branch:
      - master
      event:
      - push
  - name: lint-website
    image: node:lts-alpine
    commands:
      - "yarn lint:website"
    when:
      branch:
      - master
      event:
      - push
    depends_on:
    - build-cache
  - name: lint-server
    image: node:lts-alpine
    commands:
      - "yarn lint:server"
    when:
      branch:
      - master
      event:
      - push
    depends_on:
    - build-cache
  - name: build-website
    image: node:lts-alpine
    commands:
      - "APPLICATION_NAME=Devpunk API_SERVER_URL=https://www.devpunk.io NODE_ENV=production yarn workspace @devpunk/website build"
    when:
      branch:
      - master
      event:
      - push
    depends_on:
    - lint-website
    - lint-server
  - name: build-server
    image: node:lts-alpine
    commands:
      - "yarn workspace @devpunk/server build"
    when:
      branch:
      - master
      event:
      - push
    depends_on:
    - lint-website
    - lint-server
  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: reezpatel/devpunk
      tags:
        - latest
        - ${DRONE_COMMIT:0:8}
    when:
      branch:
      - master
      event:
      - push
    depends_on:
    - build-server
    - build-website
  - name: deploy
    image: alpine/helm:3.2.1
    environment:
      KUBECONFIG_FILE:
        from_secret: KUBECONFIG
      MONGODB_PASSWORD:
        from_secret: MONGODB_PASSWORD
      MONGODB_USERNAME:
        from_secret: MONGODB_USERNAME
      MONGODB_HOST:
        from_secret: MONGODB_HOST
      GITHUB_LOGIN_CLIENT_ID:
        from_secret: GITHUB_LOGIN_CLIENT_ID
      GITHUB_LOGIN_CLIENT_SECRET:
        from_secret: GITHUB_LOGIN_CLIENT_SECRET
      REDIS_HOST:
        from_secret: REDIS_HOST
      ADMIN_USER:
        from_secret: ADMIN_USER
      INGESTION_KEY:
        from_secret: INGESTION_KEY
    commands:
      - echo "$KUBECONFIG_FILE" > kubeconfig.b64
      - export KUBECONFIG="$PWD/kubeconfig.yml"
      - base64 -d kubeconfig.b64 > kubeconfig.yml
      - helm repo add mychart https://reezpatel.github.io/helm_charts
      - echo "$KUBECONFIG_FILE"
      - helm repo update
      - helm search repo dev
      - helm upgrade --install devpunk mychart/devpunk -n devpunk -f helm.values.yml --set-string image.tag="${DRONE_COMMIT:0:8}" --set-string env.MONGODB_PASSWORD="$MONGODB_PASSWORD" --set-string env.MONGODB_USERNAME="$MONGODB_USERNAME" --set-string env.MONGODB_HOST="$MONGODB_HOST" --set-string env.GITHUB_LOGIN_CLIENT_ID="$GITHUB_LOGIN_CLIENT_ID" --set-string env.GITHUB_LOGIN_CLIENT_SECRET="$GITHUB_LOGIN_CLIENT_SECRET" --set-string env.ADMIN_USER="$ADMIN_USER" --set-string env.REDIS_HOST="$REDIS_HOST" --set-string env.INGESTION_KEY="$INGESTION_KEY"
    when:
      event:
        - promote
      target:
        - production
    depends_on:
    - build-image
